FROM debian:bookworm

# Install packages
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/London
RUN set -ex \
    && apt-get update \
    && apt-get install -qq --no-install-recommends ca-certificates dirmngr gosu gpg wget libatomic1 python3 \
    && apt-get install -qq --no-install-recommends g++ build-essential libtool autotools-dev automake pkg-config bsdmainutils \
    && apt-get install -qq --no-install-recommends libssl-dev libevent-dev libdb-dev libdb++-dev libminiupnpc-dev libzmq3-dev \
    && apt-get install -qq --no-install-recommends python3-zmq python3-ecdsa python3-bip32utils \
    && apt-get install -qq --no-install-recommends libgoogle-perftools-dev \
    && rm -rf /var/lib/apt/lists/*

# Install boost from distribution, if required
<% if not boost_version -%>
RUN set -ex \
    && apt-get update \
    && apt-get install -qq --no-install-recommends libboost-system-dev \
    && apt-get install -qq --no-install-recommends libboost-filesystem-dev \
    && apt-get install -qq --no-install-recommends libboost-chrono-dev \
    && apt-get install -qq --no-install-recommends libboost-program-options-dev \
    && apt-get install -qq --no-install-recommends libboost-test-dev \
    && apt-get install -qq --no-install-recommends libboost-thread-dev \
    && rm -rf /var/lib/apt/lists/*
<% end -%>
